### ISSUE TITLE
QuickLook as a floating window

### ISSUE THREAD

**Issue by ronaldsuwandi** [mikekazakov/nc#69]
As mentioned in the forum: http://magnumbytes.com/forum/viewtopic.php?f=6&t=190

Just thought it's a good idea to move the thread in here

**Comment by mikekazakov** [comment]
Done in v1.2.3.

**Comment by ronaldsuwandi** [comment]
@mikekazakov I downloaded 1.2.3 but quicklook is still not shown on a floating window

**Comment by mikekazakov** [comment]
This behavior is configurable; default setting didn't change.
Check the option in Preferences->Panels->Presentation.
